/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-roomv2.glb --transform 
Files: optimized-roomv2.glb [1.48MB] > C:\Users\Muaz\Desktop\ahmedmuazatik_3dportfolio\public\models\optimized-roomv2-transformed.glb [89.46KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/optimized-roomv2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.window_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.c.geometry} material={materials.black01} position={[-0.803, 2.425, -2.363]} rotation={[Math.PI / 2, 0, -0.413]} scale={0.514} />
      <mesh geometry={nodes.emis_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.window4_phong1_0.geometry} material={materials.phong1} />
    </group>
  )
}

useGLTF.preload('/optimized-roomv2-transformed.glb')
